/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.adenur.sisfo.view;

import com.adenur.sisfo.dao.DAOFactory;
import com.adenur.sisfo.dao.GuruDAO;
import com.adenur.sisfo.dao.UserDAO;
import java.sql.Connection;

/**
 *
 * @author sadlie
 */
public class FrameUser extends javax.swing.JFrame {
    
    private Connection connection;
    private GuruDAO guruDAO;
    private UserDAO userDAO;

    /**
     * Creates new form FrameUser
     */
    public FrameUser() {
        initComponents();
    }
    
    public FrameUser(Connection connection) {
        this.connection = connection;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        panelDataDasar = new javax.swing.JPanel();
        panelAkunAplikasi = new javax.swing.JPanel();
        lUsername = new javax.swing.JLabel();
        lPassword = new javax.swing.JLabel();
        lKonfirmasi = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        pfPassword1 = new javax.swing.JPasswordField();
        pfPassword2 = new javax.swing.JPasswordField();
        bCancel = new javax.swing.JButton();
        bSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout panelDataDasarLayout = new javax.swing.GroupLayout(panelDataDasar);
        panelDataDasar.setLayout(panelDataDasarLayout);
        panelDataDasarLayout.setHorizontalGroup(
            panelDataDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        panelDataDasarLayout.setVerticalGroup(
            panelDataDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Data Dasar", panelDataDasar);

        lUsername.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lUsername.setText("Username :");

        lPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lPassword.setText("Password :");

        lKonfirmasi.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lKonfirmasi.setText("Konfirmasi :");

        javax.swing.GroupLayout panelAkunAplikasiLayout = new javax.swing.GroupLayout(panelAkunAplikasi);
        panelAkunAplikasi.setLayout(panelAkunAplikasiLayout);
        panelAkunAplikasiLayout.setHorizontalGroup(
            panelAkunAplikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAkunAplikasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAkunAplikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lKonfirmasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAkunAplikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pfPassword2, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addComponent(tfUsername)
                    .addComponent(pfPassword1))
                .addContainerGap())
        );
        panelAkunAplikasiLayout.setVerticalGroup(
            panelAkunAplikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAkunAplikasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAkunAplikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lUsername)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAkunAplikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPassword)
                    .addComponent(pfPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAkunAplikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lKonfirmasi)
                    .addComponent(pfPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Akun Aplikasi", panelAkunAplikasi);

        bCancel.setText("Batal");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        bSave.setText("Simpan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbedPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCancel)
                    .addComponent(bSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bCancelActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        guruDAO = (GuruDAO)DAOFactory.init(connection).get(DAOFactory.Type.GURU);
        userDAO = (UserDAO)DAOFactory.init(connection).get(DAOFactory.Type.USER);
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bSave;
    private javax.swing.JLabel lKonfirmasi;
    private javax.swing.JLabel lPassword;
    private javax.swing.JLabel lUsername;
    private javax.swing.JPanel panelAkunAplikasi;
    private javax.swing.JPanel panelDataDasar;
    private javax.swing.JPasswordField pfPassword1;
    private javax.swing.JPasswordField pfPassword2;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
